version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "81:81"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=phpecommerce
            - MYSQL_USER=root
            - MYSQL_PASSWORD=1234
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
